plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "com.sina.dexandjarconverter"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.sina.dexandjarconverter"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }



        signingConfigs {
        create("release") {
            // Add ../ to tell Gradle to look in the parent directory
            storeFile = file("/storage/emulated/0/AndroidIDEProjects/DexAndJarConverter/app/converter-release.jks") 
            storePassword = "AndroidIDE123" 
            keyAlias = "converter-key"
            keyPassword = "AndroidIDE123"   
        }
    }

    
 buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true // Also removes unused XML/drawables
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            signingConfig = signingConfigs.getByName("release")
            
        }
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
    
    
implementation("de.femtopedia.dex2jar:dex-translator:2.4.36")
    implementation("de.femtopedia.dex2jar:dex-tools:2.4.36")
implementation("com.android.tools:r8:8.3.37") 
implementation("org.smali:smali:2.5.2")
implementation("org.smali:baksmali:2.5.2")

}
